# Generated by Django 3.2.5 on 2021-12-30 12:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('re_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_date', models.DateField()),
                ('user', models.IntegerField()),
                ('day', models.IntegerField()),
                ('people', models.IntegerField()),
                ('plane', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
                ('acc', models.IntegerField()),
                ('activity', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
            ],
            options={
                'db_table': 'pay',
            },
        ),
    ]
