export { default as Navigation } from 'features/common/components/Navigation'
export { default as Header } from 'features/common/components/Header'
export { default as Dashboard } from 'features/common/components/Dashboard'

export { default as Budget } from 'features/common/components/Budget'
export { default as LatestOrders } from 'features/common/components/LatestOrders'
export { default as LatestSales } from 'features/common/components/LatestSales'
export { default as TotalCustomers } from 'features/common/components/TotalCustomers'
export { default as TotalProfit } from 'features/common/components/TotalProfit'
export { default as TrafficByDevice } from 'features/common/components/TrafficByDevice'
export { default as GlobalStyles } from 'features/common/components/GlobalStyles'
